
package net.joaolourenco.fallen;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FallenSystem", targetNamespace = "http://fallen.joaolourenco.net/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FallenSystem {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(operationName = "GetGameVersions")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetGameVersions", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.GetGameVersions")
    @ResponseWrapper(localName = "GetGameVersionsResponse", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.GetGameVersionsResponse")
    @Action(input = "http://fallen.joaolourenco.net/FallenSystem/GetGameVersionsRequest", output = "http://fallen.joaolourenco.net/FallenSystem/GetGameVersionsResponse")
    public List<String> getGameVersions();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ManageBan")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ManageBan", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.ManageBan")
    @ResponseWrapper(localName = "ManageBanResponse", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.ManageBanResponse")
    @Action(input = "http://fallen.joaolourenco.net/FallenSystem/ManageBanRequest", output = "http://fallen.joaolourenco.net/FallenSystem/ManageBanResponse")
    public String manageBan(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CheckLauncherVersion")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CheckLauncherVersion", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.CheckLauncherVersion")
    @ResponseWrapper(localName = "CheckLauncherVersionResponse", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.CheckLauncherVersionResponse")
    @Action(input = "http://fallen.joaolourenco.net/FallenSystem/CheckLauncherVersionRequest", output = "http://fallen.joaolourenco.net/FallenSystem/CheckLauncherVersionResponse")
    public String checkLauncherVersion();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CheckGameVersion")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CheckGameVersion", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.CheckGameVersion")
    @ResponseWrapper(localName = "CheckGameVersionResponse", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.CheckGameVersionResponse")
    @Action(input = "http://fallen.joaolourenco.net/FallenSystem/CheckGameVersionRequest", output = "http://fallen.joaolourenco.net/FallenSystem/CheckGameVersionResponse")
    public String checkGameVersion();

    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreateUser")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CreateUser", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.CreateUser")
    @ResponseWrapper(localName = "CreateUserResponse", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.CreateUserResponse")
    @Action(input = "http://fallen.joaolourenco.net/FallenSystem/CreateUserRequest", output = "http://fallen.joaolourenco.net/FallenSystem/CreateUserResponse")
    public String createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteUser")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "DeleteUser", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.DeleteUser")
    @ResponseWrapper(localName = "DeleteUserResponse", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.DeleteUserResponse")
    @Action(input = "http://fallen.joaolourenco.net/FallenSystem/DeleteUserRequest", output = "http://fallen.joaolourenco.net/FallenSystem/DeleteUserResponse")
    public String deleteUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ChangeUserAccount")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ChangeUserAccount", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.ChangeUserAccount")
    @ResponseWrapper(localName = "ChangeUserAccountResponse", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.ChangeUserAccountResponse")
    @Action(input = "http://fallen.joaolourenco.net/FallenSystem/ChangeUserAccountRequest", output = "http://fallen.joaolourenco.net/FallenSystem/ChangeUserAccountResponse")
    public String changeUserAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ManageUser")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ManageUser", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.ChangeUserAccount")
    @ResponseWrapper(localName = "ManageUserResponse", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.ChangeUserAccountResponse")
    @Action(input = "http://fallen.joaolourenco.net/FallenSystem/ManageUserRequest", output = "http://fallen.joaolourenco.net/FallenSystem/ManageUserResponse")
    public String manageUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Login")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Login", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.LoginResponse")
    @Action(input = "http://fallen.joaolourenco.net/FallenSystem/LoginRequest", output = "http://fallen.joaolourenco.net/FallenSystem/LoginResponse")
    public String login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Logout")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Logout", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.Logout")
    @ResponseWrapper(localName = "LogoutResponse", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.LogoutResponse")
    @Action(input = "http://fallen.joaolourenco.net/FallenSystem/LogoutRequest", output = "http://fallen.joaolourenco.net/FallenSystem/LogoutResponse")
    public String logout(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "AddUser")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AddUser", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.AddUser")
    @ResponseWrapper(localName = "AddUserResponse", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.AddUserResponse")
    @Action(input = "http://fallen.joaolourenco.net/FallenSystem/AddUserRequest", output = "http://fallen.joaolourenco.net/FallenSystem/AddUserResponse")
    public String addUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Update")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Update", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.Update")
    @ResponseWrapper(localName = "UpdateResponse", targetNamespace = "http://fallen.joaolourenco.net/", className = "net.joaolourenco.fallen.UpdateResponse")
    @Action(input = "http://fallen.joaolourenco.net/FallenSystem/UpdateRequest", output = "http://fallen.joaolourenco.net/FallenSystem/UpdateResponse")
    public String update();

}
